SwissDataScienceCenter/renku-actions

deploy-renku/entrypoint.sh

Mirroring https://github.com/SwissDataScienceCenter/renku/pull/2206

Parametrize rancher API endpoint

---

check-pr-description/README.md
deploy-renku/README.md

Adds docs for the deploy action and updates docs for the check-pr-description action.

chore: add docs for deploy action

---

publish-chart/publish-chart.sh

See https://github.com/actions/checkout/issues/760

build: configuration changes to adapt to new git version

---

cleanup-renku-ci-deployments/entrypoint.sh

Minor but important fix to the script that deletes jupyter servers.

chore: fix ci deployment cleanup script

---

deploy-renku/deploy-dev-renku.py

Changes to build action for the new, unified UI chart.
This is a companion to https://github.com/SwissDataScienceCenter/renku-ui/pull/1942.

build: unify ui and ui-server charts

---

rollout-renku-version/rollout-renku-deployment.sh

After recent changes to UI chart, the spacing on welcome message has changed, this PR makes adjustments for that.

fix: rollout spacing

---

cleanup-renku-ci-deployments/entrypoint.sh
deploy-renku/entrypoint.sh
teardown-renku/entrypoint.sh

GitLab URL to be set as an environment variable, and add `set -e` to ensure script fails if command fails

chore: change gitlab url

---

check-pr-description/README.md
check-pr-description/action.yaml
test-renku-cypress/README.md
test-renku-cypress/action.yml

Support handling `#cypress` in the deploy command.
fix #44

feat: support running cypress tests

---

.github/workflows/update-on-new-release.yaml
deploy-renku/README.md
publish-chart/README.md
rollout-renku-version/README.md
update-component-version/README.md

Updates checkout action version.

chore: update checkout action

---

deploy-renku/deploy-dev-renku.py

the new code failed when doing slash-deploy with something like `renku-core=my-branch` since version isn't a valid semver version in that case.

fix setting rp cli version for branch references

---

test-renku-cypress/action.yml

Now I see why videos and screenshots were not uploaded :unamused:

fix: use input variable properly

---

test-renku-cypress/action.yml

fix: set cache dependency path

---

test-renku-cypress/action.yml

chore: fix inputs

---

.gitignore

accidentally committed an tooling config file that's not relevant.

add vscode and rope to gitignore

---

publish-chart/Dockerfile
publish-chartpress-images/publish-images.sh

Solves this: https://github.com/SwissDataScienceCenter/renku/runs/17466872596

fix: installing chartpress in publish chart action

---

publish-chartpress-images/Dockerfile

Same issue as what was fixed in #69 but for another action.

fix: publish chart images action

---

update-component-version/Dockerfile
update-component-version/update-upstream.sh

When yq outputs a file it has a bad formatting (i.e. one that no
formatter is happy with) and there is no option to enable
formatting.
Therefore with this commit we add a formatter that fix the file
after yq does its thing.

feat(update-upstream): Format the values file after it is merged.

---

.github/workflows/update-on-new-release.yaml

[`renku-data-services`](https://github.com/SwissDataScienceCenter/renku-data-services) contains GitHub actions from here.
See: https://github.com/SwissDataScienceCenter/renku-data-services/blob/main/.github/workflows/acceptance-tests.yml

feat: add renku-data-services to the list of supported repositories

---

check-pr-description/action.yaml
deploy-renku/README.md
deploy-renku/deploy-dev-renku.py

Adds the ability to install the new amalthea helm chart when renku is deployed.

feat: add new amalthea helm chart

---

check-pr-description/action.yaml
test-renku/action.yml

This adds another matcher to enable/disable legacy tests conveniently.

feat: add a second string matcher to conveniently enable/disable legacy tests

---

cleanup-renku-ci-deployments/README.md
cleanup-renku-ci-deployments/entrypoint.sh
deploy-renku/README.md
deploy-renku/entrypoint.sh
test-renku/README.md
test-renku/action.yml
test-renku/entrypoint.sh

This will instead use the KUBECONFIG variable which is standard and points to a valid kubeconfig file.

feat: remove the use of RENKUBOT_KUBECONFIG
