SwissDataScienceCenter/renku-actions

generate-crd-docs/Dockerfile, generate-crd-docs/README.md, generate-crd-docs/action.yaml
See https://github.com/SwissDataScienceCenter/amalthea/pull/78 and in particular https://github.com/SwissDataScienceCenter/amalthea/blob/000-crd-docs2/docs/crd.md for an example of this action in use.
=> feat: add action to generate CRD md documentation from yaml

publish-chart/README.md, publish-chart/publish-chart.sh
This allows the location of the chartpress.yaml file to be specified when publishing a helm chart with chartpress.
Chartpress works only when the chartpress.yaml file is located where the chartpress command is run.
But if you have a repo where you have multiple chartpress.yaml files or you have them in a non-standard location this is useful.
=> feat: specify chartpress.yaml location when publishing

deploy-renku/entrypoint.sh
So the problem was that the if statement here was not working in alpine with a more stricter posix shell interpreter but was working fine when testing locally.
After running in the same docker image as this action I could reproduce the error.
I used [this guide](https://thoughtbot.com/blog/the-unix-shells-humble-if#the-test-command) to get a "proper posix shell syntax" for the if statement.
Tested here: https://github.com/SwissDataScienceCenter/renku-notebooks/runs/4347544686?check_suite_focus=true
It works.
Version 0.3.0 worked because the if statement was a bit different and this either triggered all the time or just triggered properly. Changing the if statement syntax was the problem - not the credentials in the secrets.
=> fix: deploy renku action

.github/workflows/update-on-new-release.yaml
Minor changes so that the action that updates all the other actions in other repos is tracking the latest version.
Also the draft release for the new version of the actions is here:
https://github.com/SwissDataScienceCenter/renku-actions/releases/tag/untagged-cf9b6808bba1e064bca7
=> chore: update action that updates actions

test-renku/action.yml
Noticed that I forgot to properly update the pinned versions of the child actions in the large renku-test composite action.
=> fix: change versions of child actions test-renku

deploy-renku/README.md, deploy-renku/entrypoint.sh
Now that all devs including renkubot are admins in the dev cluster, this allows us to simplify things quite a bit.
Deploy action seems to work, see https://github.com/SwissDataScienceCenter/renku/pull/2444.
=> chore: create ci ns independent of rancher

cleanup-renku-ci-deployments/entrypoint.sh
So the problem with the action was as follows, when a CI deployment does not have `#persist` then the CI deployment is deleted as soon as the tests finish. But the namespace is left until the PR is closed. However the main deletion logic in the action was based on looping over helm releases. So if there is no helm release it would do nothing. So when the PR is closed the only thing left to clean up is the namespace - there is no helm release. So the action would leave the namespaces out.
Now the logic loops first through the namespaces and then through the releases. So even if a release is not there it can catch the existence of an empty namespace and delete the namespace.
See test action: https://github.com/SwissDataScienceCenter/renku-notebooks/runs/5286353491?check_suite_focus=true#step …
=> fix: fully cleanup namespaces from CI deployments

.github/workflows/update-on-new-release.yaml
renku-graph uses `development` as their main branch. It used to be master. This way the automated PRs that update the action version will work.
=> chore(ci): correct branch for action update

deploy-renku/Dockerfile
Helm <3.8 has an issue where large numbers like `1073741824` get turned into scientific notation like `1.073741824e+09` which can break things further down the line (e.g. converting an env variable back to int).
Bumping the base image updates helm to version 3.9.0, which does not have this issue.
=> chore: bump base image for deploy to fix issue with helm number formatting

download-test-artifacts/Dockerfile, download-test-artifacts/action.yml, download-test-artifacts/entrypoint.sh, test-renku/action.yml
The two actions are refactored to be more generic and not require
a values file, taking the reference to the S3 bucket holding
the test artifacts as input instead.
This is part of a larger work that will allow running the acceptance-tests
from the Github actions also for permanent deployments of Renku in addition
to the PR-deployments.
=> chore: Refactor dowload-test-artifacts and test-renku for more generalization

rollout-renku-version/Dockerfile, rollout-renku-version/rollout-renku-deployment.sh
This new version of `yq` does not change the existing
formatting of the YAML file it edits.
=> chore(rollout-renku-version): upgrade yq to 4.27.5

.github/workflows/update-on-new-release.yaml
Dependabot already takes care of this, see e.g. https://github.com/SwissDataScienceCenter/renku-python/pull/3156
=> remove renku-python from update-on-release-action

rollout-renku-version/rollout-renku-deployment.sh
Do not try to extract CHART_VERSION from Chart.yaml as we
no longer update it. Instead simply require that the tag
be passed to the action.
=> feat(rollout-renku-version): Accept CHART_VERSION as env.

check-pr-description/action.yaml
As per [this announcement](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), the set-output & set-state commands are deprecated. This PR replaces them with the new approach to setting outputs.
=> chore: replace set-output commands

check-pr-description/action.yaml
Updates the `check-pr-description` action to handle PRs with no description set.
=> fix(check-pr-description): handle empty PR description

test-renku-cypress/README.md, test-renku-cypress/action.yml
Port the logic from https://github.com/SwissDataScienceCenter/renku/pull/3150
After merging this PR, I will tag a new release and update the corresponding actions in the other Renku repositories.
=> feat: update Cypress tests with a new running strategy

deploy-renku/deploy-dev-renku.py, test-renku/action.yml
A couple of changes to the deploy action:
* Add `--wait` and `--wait-for-jobs` to the `helm upgrade` command to prevent marking the environment ready too soon and running tests early (ref: https://helm.sh/docs/helm/helm_upgrade/#options )
=> Improve deploy action

check-pr-description/README.md, check-pr-description/action.yaml, test-renku-cypress/README.md, test-renku-cypress/action.yml, test-renku/README.md, test-renku/action.yml
With recent updates on the acceptance tests, we _always_ use the `#persist` flag. We can get rid of it.
I suggest implementing a more aggressive strategy to regularly cull CI deployments that have been running for some time without changes (3 days?)
=> chore: remove the #persist flag

publish-chartpress-images/publish-images.sh
This error shows up when we try to publish images with chartpress:
```
+ cd .
+ chartpress --push --tag 1.19.1
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
Leaving helm-chart/renku-notebooks/Chart.yaml version unchanged: 1.19.1
```
To avoid this, we change the config in the action to trust the repo. As I see it this happens because the github checkout step may run as a different user than the chartpress step.
I looked at this article for help:
https://medium.com/@janloo/github-actions-detected-dubious-ownership-in-repository-at-github-workspace-how-to-fix-b9cc127d4c04
=> fix: trust local git repo when running chartpress

publish-chart/Dockerfile
This is required to correctly handle OCI Helm repositories.
=> chore: Update Helm in publish-chart to latest version.

test-renku-cypress/action.yml
It is better to always run with the LTS node version IMO.
=> chore: update node and cypress action

publish-chart/Dockerfile, publish-chartpress-images/Dockerfile, update-component-version/Dockerfile
Fixes `publish-chart`, `publish-chartpress-images` and `update-component-version` which were broken by #84.
Example: https://github.com/SwissDataScienceCenter/renku-notebooks/actions/runs/9192250296/job/25282800881#step:2:36.
=> fix: correct pip3 invocation for requests<2.32.0

check-pr-description/action.yaml
Resolving conflicts in the new actions release caused this small issue.
It took me trial and error to find the missing `fi`.
=> fix: check pr description action

test-renku/action.yml
The upload-artifact version used by the selenium tests was out of date, and github was refusing to run the action as a result. This updates to the current version of [upload-artifact](https://github.com/actions/upload-artifact).
The action was tested in https://github.com/SwissDataScienceCenter/renku-ui/actions/runs/10808535902/job/29982169525?pr=3275
=> fix: update the version of the upload-artifact action

publish-chartpress-images/README.md, publish-chartpress-images/publish-images.sh
Changes the publish-chartpress-images action to optionally push images tagged with 'latest'.
=> feat: add option to push latest image

test-renku-cypress/action.yml
v3 is deprecated
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> chore: bump actions/upload-artifact@v4

deploy-renku/Dockerfile, deploy-renku/entrypoint.sh
This prepares the action to work with a base values file that comes directly from the Renku repository itself instead of the Github secrets.
I have tested this action here: https://github.com/SwissDataScienceCenter/renku/pull/3921
=> feat: Use the base value file for CI deployment from the Renku repo

test-renku-cypress/action.yml
This should prevent overwriting the uploaded videos from different tests.
The PR also bumps the actions we are consuming
=> fix: use different names for cypress tests artifacts to prevent overwriting

test-renku-cypress/action.yml
This should avoid unnecessary errors and confusing logs when earli steps fail
=> improve steps chaining

test-renku-cypress/README.md, test-renku-cypress/action.yml
This fails the tests when the target spec is missing, so they don't mistakenly appear as passed because the spec for checking the infrastructure still runs.
It also improves the `if: failure()` logic to avoid unnecessary warnings for artifacts.
=> feat: fail cypress tests when then spec is missing

test-renku-cypress/action.yml
Removes `continue-on-error: true`  to fix the wrongly reported outcome of Cypress tests.
Supersedes #110
=> fix: remove continue-on-error
